---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-home-pv-claim
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://eu-central-1/vol-id
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   labels:
     app: jenkins
   name: jenkins-home-pv-claim
spec:
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 3Gi
   storageClassName: gp2
---